status = warn
name = Log4j2PropertiesConfig

appenders = console, file, roll

appender.roll.type = RollingFile
appender.roll.name = RollingFileAppender
appender.roll.fileName = logs/roll-application.log
# ???????? ???????? ?? %d{yyyy-MM-dd} ? ?? ???? ?????? ????????, ??? ????? ?????? ???? ?? ????.
# %i ? ??? ??????? (1, 2, 3), ???? ?? ???? ? ??? ?? ???? ????????? ????????? ???????.
# ?????????? .gz ? ????? ???????? Log4j2 ????????????? ??????? ?????? ? ZIP/GZ (???? ?????????? ? 10 ???!).
appender.roll.filePattern = logs/archive/app-%d{yyyy-MM-dd}-%i.log.gz
appender.roll.layout.type = PatternLayout
appender.roll.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
# ???????? (Triggers) ? ???????, ??? ??????? ???? ???? ?????????????
appender.roll.policies.type = Policies
# ??????? ?1: ?? ??????? (?????? ?????)
appender.roll.policies.time.type = TimeBasedTriggeringPolicy
appender.roll.policies.time.interval = 1
appender.roll.policies.time.modulate = true
# ??????? ?2: ?? ??????? (??? ?????? ???? ?????? ?? 10 ????????)
appender.roll.policies.size.type = SizeBasedTriggeringPolicy
appender.roll.policies.size.size = 10MB
# ????????? (Strategy) ? ??? ?????? ?? ?????.?? ?????????
appender.roll.strategy.type = DefaultRolloverStrategy
# ??????? ??????? ???????? 7 ???????? ?????? ?? ???? ???? (???? ????????? ?????? ? ????? ?????? ?? ???? ???? ????????)
appender.roll.strategy.max = 7

appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.target = SYSTEM_OUT
#appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
#appender.console.layout.pattern = %style{%d{HH:mm:ss.SSS}}{cyan} %highlight{[%-5level]} %style{[%t]}{bold blue} %style{%c{1}:%L}{magenta} - %msg%n

appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/application.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

rootLogger.level = info
rootLogger.appenderRefs = console, file, roll
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.file.ref = FileAppender
rootLogger.appenderRef.roll.ref = RollingFileAppender

loggers = fileServiceLogger
logger.fileServiceLogger.name = org.example.testrestsoap
logger.fileServiceLogger.level = trace