DROP TABLE IF EXISTS test_counters;

CREATE TABLE test_counters
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255)   NOT NULL,
    counter NUMERIC(19, 4) NOT NULL
);

CREATE TABLE passports
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passport_number VARCHAR(50) NOT NULL
);

CREATE TABLE addresses
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL
);

CREATE TABLE persons
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    age        NUMERIC(19, 4) NOT NULL,
    passport_id BIGINT UNIQUE,
    address_id  BIGINT,
    FOREIGN KEY (passport_id) REFERENCES passports (id),
    FOREIGN KEY (address_id) REFERENCES addresses (id)
);

CREATE TABLE companies
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);


CREATE TABLE person_companies
(
    person_id  BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    PRIMARY KEY (person_id, company_id),
    FOREIGN KEY (person_id) REFERENCES persons (id),
    FOREIGN KEY (company_id) REFERENCES companies (id)
);